// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjoOI5JUezs3wFpLLwBRAk3MOJKzJz5EM',
    appId: '1:529136837541:web:2d5ef60229011d064b7e4c',
    messagingSenderId: '529136837541',
    projectId: 'chat-app-197f0',
    authDomain: 'chat-app-197f0.firebaseapp.com',
    storageBucket: 'chat-app-197f0.firebasestorage.app',
    measurementId: 'G-7NDEZEF4B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3nySXAos1Zyl8VRgNcN6pODOOFBIC9Ek',
    appId: '1:529136837541:android:60a642981cb0a1694b7e4c',
    messagingSenderId: '529136837541',
    projectId: 'chat-app-197f0',
    storageBucket: 'chat-app-197f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk3sp_hh7TYtetAl9vxYLGf20poncMntM',
    appId: '1:529136837541:ios:55494380bb30d1124b7e4c',
    messagingSenderId: '529136837541',
    projectId: 'chat-app-197f0',
    storageBucket: 'chat-app-197f0.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk3sp_hh7TYtetAl9vxYLGf20poncMntM',
    appId: '1:529136837541:ios:55494380bb30d1124b7e4c',
    messagingSenderId: '529136837541',
    projectId: 'chat-app-197f0',
    storageBucket: 'chat-app-197f0.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjoOI5JUezs3wFpLLwBRAk3MOJKzJz5EM',
    appId: '1:529136837541:web:4d3e24c6fa341b2f4b7e4c',
    messagingSenderId: '529136837541',
    projectId: 'chat-app-197f0',
    authDomain: 'chat-app-197f0.firebaseapp.com',
    storageBucket: 'chat-app-197f0.firebasestorage.app',
    measurementId: 'G-8RCM61VZSV',
  );

}