// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ7kNYOLsyIcpnbJMOz98xLdytm5Dj1q8',
    appId: '1:1026904357957:web:15f0ac54aca31eb046f72c',
    messagingSenderId: '1026904357957',
    projectId: 'flutter-chat-app-7ac2f',
    authDomain: 'flutter-chat-app-7ac2f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7ac2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8s3d3tTnqUOKidiMSdM4ZLWV2TCXSsOQ',
    appId: '1:1026904357957:android:0514d6d9d05b3eeb46f72c',
    messagingSenderId: '1026904357957',
    projectId: 'flutter-chat-app-7ac2f',
    storageBucket: 'flutter-chat-app-7ac2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV3UtXUGuyhCBg6UOXmECOyIKxquc4Bh4',
    appId: '1:1026904357957:ios:c741164f55f3988046f72c',
    messagingSenderId: '1026904357957',
    projectId: 'flutter-chat-app-7ac2f',
    storageBucket: 'flutter-chat-app-7ac2f.appspot.com',
    iosClientId: '1026904357957-dun7fd34r4ho912ejr0a6eeilh6qkpl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV3UtXUGuyhCBg6UOXmECOyIKxquc4Bh4',
    appId: '1:1026904357957:ios:c741164f55f3988046f72c',
    messagingSenderId: '1026904357957',
    projectId: 'flutter-chat-app-7ac2f',
    storageBucket: 'flutter-chat-app-7ac2f.appspot.com',
    iosClientId: '1026904357957-dun7fd34r4ho912ejr0a6eeilh6qkpl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
